# 激活actuator 部分端点
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health,beans
# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_admin?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 19990210
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
logging:
  config: classpath:log4j2/log4j2-spring-dev.xml